/* EDIT THIS FILE to change translations.
   ui      → English text on the page  :  translated text   (exact English text is the key)
   html    → for the few headings that contain <em>/<br>, keyed by data-i18n
   content → translated versions of the structured content in content.js (same shape;
             arrays match content.js by position). Anything not listed here stays English.
   News articles are English-only for now; add a "news" array here to translate them. */
window.SITE_TRANSLATIONS = {

/* =============================== မြန်မာ =============================== */
my: {
  html: {
    aboutUsTitle: 'ကျွန်ုပ်တို့<em>အကြောင်း</em>'
  },
  ui: {
    // Navigation & common
    'Home':'ပင်မ','About':'အကြောင်း','Programs':'အစီအစဉ်များ','News':'သတင်း','Success':'အောင်မြင်မှု','Admissions':'ဝင်ခွင့်','FQ&A':'အမေးအဖြေ','Portal':'ပေါ်တယ်',
    'Student Portal':'ကျောင်းသားပေါ်တယ်','News article':'သတင်းဆောင်းပါး',
    'Skip to content':'အကြောင်းအရာသို့ ကျော်သွားရန်','Menu ☰':'မီနူး ☰','Search programs':'အစီအစဉ်များ ရှာဖွေရန်','Switch to dark mode':'အမှောင်မုဒ်သို့ ပြောင်းရန်','Switch to light mode':'အလင်းမုဒ်သို့ ပြောင်းရန်',
    'Go Go Education home':'Go Go Education ပင်မစာမျက်နှာ','Main navigation':'ပင်မလမ်းညွှန်','Close details':'အသေးစိတ်ကို ပိတ်ရန်',
    'Opening doors.':'တံခါးများ ဖွင့်ပေးခြင်း။','Expanding possibilities.':'အခွင့်အလမ်းများ တိုးချဲ့ခြင်း။','Explore':'လေ့လာရန်','Programs & courses':'အစီအစဉ်များနှင့် သင်တန်းများ','Why choose us':'ကျွန်ုပ်တို့ကို ဘာကြောင့်ရွေးသင့်သလဲ',
    'Stay inspired':'စိတ်အားထက်သန်စွာ','Student journeys':'ကျောင်းသားများ၏ ခရီးလမ်း','News & events':'သတင်းနှင့် ပွဲများ','Let’s connect':'ဆက်သွယ်ကြပါစို့','Speak to an advisor ↗':'အကြံပေးနှင့် ဆွေးနွေးရန် ↗','Student portal':'ကျောင်းသားပေါ်တယ်',
    'Made for your next chapter.':'သင့်နောက်ထပ်အခန်းကဏ္ဍအတွက် ဖန်တီးထားသည်။','Back to top ↑':'အပေါ်သို့ ပြန်သွားရန် ↑','Talk about your next step ↗':'သင့်နောက်တစ်ဆင့်အကြောင်း ဆွေးနွေးရန် ↗',
    'Explore program':'အစီအစဉ်ကို လေ့လာရန်','Primary destination':'အဓိကပန်းတိုင်',
    // Home
    'BIG DREAMS. NEW POSSIBILITIES.':'ကြီးမားသောအိပ်မက်များ။ အခွင့်အလမ်းသစ်များ။','Discover our programs':'ကျွန်ုပ်တို့၏ အစီအစဉ်များကို လေ့လာရန်','Talk to an advisor':'အကြံပေးနှင့် ဆွေးနွေးရန်',
    // About
    'Est. 2022':'၂၀၂၂ တည်ထောင်','Yangon, Myanmar':'ရန်ကုန်၊ မြန်မာ','WHO WE ARE':'ကျွန်ုပ်တို့အကြောင်း',
    'Go Go Hankuk Consultancy Company was established in 2022 with the vision of empowering Myanmar students to achieve their academic and career dreams.':'Go Go Hankuk Consultancy Company ကို မြန်မာကျောင်းသားများ ၎င်းတို့၏ ပညာရေးနှင့် အသက်မွေးဝမ်းကျောင်းဆိုင်ရာ အိပ်မက်များ အောင်မြင်စေရန် ရည်မှန်းချက်ဖြင့် ၂၀၂၂ ခုနှစ်တွင် တည်ထောင်ခဲ့ပါသည်။',
    'Over the past 3 years, we have successfully guided approximately over 700 students, providing them with tailored solutions to navigate educational challenges both in Myanmar and abroad. With over three years of experience, we are committed to continuously improving our services to help youths achieve brighter futures.':'လွန်ခဲ့သော ၃ နှစ်အတွင်း ကျောင်းသား ၇၀၀ ကျော်ကို မြန်မာနိုင်ငံအတွင်းနှင့် နိုင်ငံရပ်ခြားရှိ ပညာရေးဆိုင်ရာ စိန်ခေါ်မှုများကို ကျော်လွှားနိုင်ရန် သင့်လျော်သော ဖြေရှင်းနည်းများဖြင့် အောင်မြင်စွာ လမ်းညွှန်ပေးနိုင်ခဲ့ပါသည်။ သုံးနှစ်ကျော် အတွေ့အကြုံဖြင့် လူငယ်များ ပိုမိုတောက်ပသော အနာဂတ်ကို ရရှိစေရန် ကျွန်ုပ်တို့၏ ဝန်ဆောင်မှုများကို အဆက်မပြတ် တိုးတက်အောင် ဆောင်ရွက်လျက်ရှိပါသည်။',
    'Our consultancy addresses the challenges students face in Myanmar while ensuring a smooth transition to peaceful and productive learning experiences abroad. By prioritizing safety and academic success, we ease parents\' concerns and provide unparalleled support. Go Go Hankuk Consultancy Company stands as a trusted leader in educational consultancy, paving the way for future generations.':'ကျွန်ုပ်တို့၏ အတိုင်ပင်ခံလုပ်ငန်းသည် မြန်မာနိုင်ငံရှိ ကျောင်းသားများ ရင်ဆိုင်နေရသော စိန်ခေါ်မှုများကို ဖြေရှင်းပေးပြီး နိုင်ငံရပ်ခြားတွင် ငြိမ်းချမ်းပြီး အကျိုးရှိသော သင်ယူမှုအတွေ့အကြုံများသို့ ချောမွေ့စွာ ကူးပြောင်းနိုင်စေရန် ဆောင်ရွက်ပေးပါသည်။ လုံခြုံရေးနှင့် ပညာရေးအောင်မြင်မှုကို ဦးစားပေးခြင်းဖြင့် မိဘများ၏ စိုးရိမ်ပူပန်မှုများကို လျော့ပါးစေပြီး နှိုင်းယှဉ်မရနိုင်သော ပံ့ပိုးမှုကို ပေးပါသည်။ Go Go Hankuk Consultancy Company သည် ပညာရေးအတိုင်ပင်ခံလုပ်ငန်းတွင် ယုံကြည်စိတ်ချရသော ခေါင်းဆောင်တစ်ဦးအဖြစ် ရပ်တည်ကာ အနာဂတ်မျိုးဆက်များအတွက် လမ်းခင်းပေးလျက်ရှိပါသည်။',
    'Established':'တည်ထောင်ခဲ့သည့်နှစ်','Students guided':'လမ်းညွှန်ပေးခဲ့သော ကျောင်းသားများ','Years of experience':'နှစ်ပေါင်း အတွေ့အကြုံ',
    'VISION':'မျှော်မှန်းချက်','Our vision':'ကျွန်ုပ်တို့၏ မျှော်မှန်းချက်',
    'To be a leading international education bridge that empowers Myanmar students to access global academic and career opportunities.':'မြန်မာကျောင်းသားများ ကမ္ဘာလုံးဆိုင်ရာ ပညာရေးနှင့် အသက်မွေးဝမ်းကျောင်း အခွင့်အလမ်းများကို ရယူနိုင်စေသည့် ဦးဆောင် နိုင်ငံတကာ ပညာရေးပေါင်းကူးတံတား ဖြစ်လာရန်။',
    'MISSION':'ရည်မှန်းချက်တာဝန်','Our mission':'ကျွန်ုပ်တို့၏ ရည်မှန်းချက်တာဝန်',
    'To deliver professional, transparent, and student-focused education consulting services':'ပရော်ဖက်ရှင်နယ်ကျပြီး ပွင့်လင်းမြင်သာကာ ကျောင်းသားဗဟိုပြု ပညာရေးအတိုင်ပင်ခံ ဝန်ဆောင်မှုများ ပေးအပ်ရန်',
    'To establish strong and sustainable partnerships with international institutions':'နိုင်ငံတကာ အဖွဲ့အစည်းများနှင့် ခိုင်မာပြီး ရေရှည်တည်တံ့သော မိတ်ဖက်ဆက်ဆံရေးများ တည်ဆောက်ရန်',
    'To support students in achieving academic success and long-term career development':'ကျောင်းသားများ ပညာရေးအောင်မြင်မှုနှင့် ရေရှည်အသက်မွေးဝမ်းကျောင်း ဖွံ့ဖြိုးတိုးတက်မှု ရရှိစေရန် ပံ့ပိုးရန်',
    'To create accessible global education pathways for future generations':'အနာဂတ်မျိုးဆက်များအတွက် လက်လှမ်းမီနိုင်သော ကမ္ဘာလုံးဆိုင်ရာ ပညာရေးလမ်းကြောင်းများ ဖန်တီးရန်',
    'CORE VALUES':'အဓိကတန်ဖိုးများ','What we stand for.':'ကျွန်ုပ်တို့ ရပ်တည်သည့် တန်ဖိုးများ။','The principles that guide every conversation, application and partnership.':'ဆွေးနွေးမှု၊ လျှောက်လွှာနှင့် မိတ်ဖက်ဆက်ဆံရေးတိုင်းကို လမ်းညွှန်ပေးသော အခြေခံမူများ။',
    'Integrity':'သမာဓိ','Upholding honesty and transparency in every process':'လုပ်ငန်းစဉ်တိုင်းတွင် ရိုးသားမှုနှင့် ပွင့်လင်းမြင်သာမှုကို ထိန်းသိမ်းခြင်း',
    'Trust':'ယုံကြည်မှု','Building long-term relationships with students and partners':'ကျောင်းသားများနှင့် မိတ်ဖက်များနှင့် ရေရှည်ဆက်ဆံရေး တည်ဆောက်ခြင်း',
    'Student Success':'ကျောင်းသားအောင်မြင်မှု','Prioritizing student outcomes and development':'ကျောင်းသားများ၏ ရလဒ်နှင့် ဖွံ့ဖြိုးတိုးတက်မှုကို ဦးစားပေးခြင်း',
    'Professional Excellence':'ပရော်ဖက်ရှင်နယ် ထူးချွန်မှု','Maintaining high standards in service delivery':'ဝန်ဆောင်မှုပေးအပ်ရာတွင် စံနှုန်းမြင့်မားစွာ ထိန်းသိမ်းခြင်း',
    'Global Collaboration':'ကမ္ဘာလုံးဆိုင်ရာ ပူးပေါင်းဆောင်ရွက်မှု','Strengthening international partnerships and networks':'နိုင်ငံတကာ မိတ်ဖက်ဆက်ဆံရေးနှင့် ကွန်ရက်များကို အားဖြည့်ခြင်း',
    'LEADERSHIP':'ခေါင်းဆောင်မှု','Meet the people':'Go Go Hankuk နောက်ကွယ်မှ','behind Go Go Hankuk.':'လူများနှင့် တွေ့ဆုံပါ။','Experienced advisors dedicated to guiding every student from first enquiry to arrival.':'ပထမဆုံးစုံစမ်းမေးမြန်းချိန်မှ ရောက်ရှိချိန်အထိ ကျောင်းသားတိုင်းကို လမ်းညွှန်ပေးရန် အပ်နှင်းထားသော အတွေ့အကြုံရှိ အကြံပေးများ။',
    'FOUNDER\'S PROFILE':'တည်ထောင်သူ၏ ကိုယ်ရေးအကျဉ်း','Zun Phu Wai':'ဇွန်ဖူးဝေ','ZUN PHU WAI':'ဇွန်ဖူးဝေ','Founder & Managing Director':'တည်ထောင်သူနှင့် စီမံခန့်ခွဲရေးဒါရိုက်တာ',
    'Zun Phu Wai is the Founder and Chief Executive Officer of Go Go Hankuk, leading the company’s strategic direction and overall operations.':'ဇွန်ဖူးဝေသည် Go Go Hankuk ၏ တည်ထောင်သူနှင့် အမှုဆောင်အရာရှိချုပ်ဖြစ်ပြီး ကုမ္ပဏီ၏ မဟာဗျူဟာလမ်းကြောင်းနှင့် လုပ်ငန်းလည်ပတ်မှု အလုံးစုံကို ဦးဆောင်ပါသည်။',
    'With a background in education consultancy and international program coordination, she has developed strong expertise in student advisory services, visa processing, and partnership development with educational institutions.':'ပညာရေးအတိုင်ပင်ခံနှင့် နိုင်ငံတကာအစီအစဉ် ညှိနှိုင်းရေး နောက်ခံဖြင့် သူမသည် ကျောင်းသားအကြံပေးဝန်ဆောင်မှု၊ ဗီဇာလုပ်ငန်းစဉ်နှင့် ပညာရေးအဖွဲ့အစည်းများနှင့် မိတ်ဖက်ဆက်ဆံရေး ဖွံ့ဖြိုးတိုးတက်မှုတို့တွင် ခိုင်မာသော ကျွမ်းကျင်မှုကို တည်ဆောက်ထားပါသည်။',
    'Since establishing Go Go Hankuk in 2022, she has played a key role in building the company into a reliable consultancy focused on South Korea and international pathway programs.':'၂၀၂၂ ခုနှစ်တွင် Go Go Hankuk ကို တည်ထောင်ပြီးကတည်းက တောင်ကိုရီးယားနှင့် နိုင်ငံတကာလမ်းကြောင်း အစီအစဉ်များကို အဓိကထားသော ယုံကြည်စိတ်ချရသည့် အတိုင်ပင်ခံလုပ်ငန်းအဖြစ် ကုမ္ပဏီကို တည်ဆောက်ရာတွင် အဓိကအခန်းကဏ္ဍမှ ပါဝင်ခဲ့ပါသည်။',
    'Her leadership is centered on delivering professional, transparent, and student-focused services, ensuring that every student receives clear guidance and support throughout their study-abroad journey.':'သူမ၏ ခေါင်းဆောင်မှုသည် ပရော်ဖက်ရှင်နယ်ကျပြီး ပွင့်လင်းမြင်သာကာ ကျောင်းသားဗဟိုပြု ဝန်ဆောင်မှုများ ပေးအပ်ရေးကို ဗဟိုပြုထားပြီး ကျောင်းသားတိုင်း နိုင်ငံရပ်ခြားပညာသင်ခရီးတစ်လျှောက် ရှင်းလင်းသော လမ်းညွှန်မှုနှင့် ပံ့ပိုးမှုကို ရရှိစေရန် သေချာစေပါသည်။',
    'Her vision is to position Go Go Hankuk as a leading Korea and international pathway education consultancy in Southeast Asia.':'သူမ၏ မျှော်မှန်းချက်မှာ Go Go Hankuk ကို အရှေ့တောင်အာရှတွင် ဦးဆောင် ကိုရီးယားနှင့် နိုင်ငံတကာလမ်းကြောင်း ပညာရေးအတိုင်ပင်ခံလုပ်ငန်းအဖြစ် နေရာယူစေရန် ဖြစ်ပါသည်။',
    'DIRECTOR\'S PROFILE':'ဒါရိုက်တာ၏ ကိုယ်ရေးအကျဉ်း','Nay Myo Thura Naing':'နေမျိုးသူရနိုင်','NAY MYO THURA NAING':'နေမျိုးသူရနိုင်','Director':'ဒါရိုက်တာ',
    'Nay Myo Thura Naing serves as the Director of Go Go Hankuk, leading the company’s branding, marketing strategy, and business development initiatives.':'နေမျိုးသူရနိုင်သည် Go Go Hankuk ၏ ဒါရိုက်တာအဖြစ် တာဝန်ထမ်းဆောင်ပြီး ကုမ္ပဏီ၏ အမှတ်တံဆိပ်တည်ဆောက်ရေး၊ စျေးကွက်မဟာဗျူဟာနှင့် စီးပွားရေးဖွံ့ဖြိုးတိုးတက်မှု လုပ်ငန်းစဉ်များကို ဦးဆောင်ပါသည်။',
    'He holds an MBA (International Program) from Siam University, Thailand, with a focus on marketing, business strategy, and the education industry.':'သူသည် ထိုင်းနိုင်ငံ Siam University မှ စျေးကွက်၊ စီးပွားရေးမဟာဗျူဟာနှင့် ပညာရေးလုပ်ငန်းကို အဓိကထားသော MBA (International Program) ဘွဲ့ကို ရရှိထားပါသည်။',
    'With nearly 10 years of experience in marketing and graphic design, he brings strong expertise in brand development, visual communication, and digital marketing. His work plays a key role in strengthening Go Go Hankuk’s professional image and positioning in the education consultancy market.':'စျေးကွက်နှင့် ဂရပ်ဖစ်ဒီဇိုင်းတွင် ၁၀ နှစ်နီးပါး အတွေ့အကြုံဖြင့် အမှတ်တံဆိပ်ဖွံ့ဖြိုးတိုးတက်ရေး၊ အမြင်ဆိုင်ရာ ဆက်သွယ်ရေးနှင့် ဒစ်ဂျစ်တယ်စျေးကွက်ရှာဖွေရေးတို့တွင် ခိုင်မာသော ကျွမ်းကျင်မှုကို ယူဆောင်လာပါသည်။ သူ၏လုပ်ငန်းသည် ပညာရေးအတိုင်ပင်ခံစျေးကွက်တွင် Go Go Hankuk ၏ ပရော်ဖက်ရှင်နယ်ပုံရိပ်နှင့် ရပ်တည်မှုကို အားဖြည့်ရာတွင် အဓိကအခန်းကဏ္ဍမှ ပါဝင်ပါသည်။',
    'At Go Go Hankuk, he is responsible for developing communication strategies, supporting business expansion, and enhancing customer experience to ensure consistent growth and brand recognition.':'Go Go Hankuk တွင် သူသည် ဆက်သွယ်ရေးမဟာဗျူဟာများ ရေးဆွဲခြင်း၊ စီးပွားရေးတိုးချဲ့မှုကို ပံ့ပိုးခြင်းနှင့် တည်ငြိမ်သော တိုးတက်မှုနှင့် အမှတ်တံဆိပ် အသိအမှတ်ပြုမှု ရရှိစေရန် ဖောက်သည်အတွေ့အကြုံကို မြှင့်တင်ခြင်းတို့အတွက် တာဝန်ရှိပါသည်။',
    'His vision is to build Go Go Hankuk into a premium and internationally recognized education consultancy brand.':'သူ၏ မျှော်မှန်းချက်မှာ Go Go Hankuk ကို အဆင့်မြင့်ပြီး နိုင်ငံတကာ အသိအမှတ်ပြု ပညာရေးအတိုင်ပင်ခံ အမှတ်တံဆိပ်အဖြစ် တည်ဆောက်ရန် ဖြစ်ပါသည်။',
    'OUR OFFICE & CLASSROOM':'ကျွန်ုပ်တို့၏ ရုံးခန်းနှင့် စာသင်ခန်း','A place to learn,':'သင်ယူရန်၊ စီစဉ်ရန်နှင့်','plan and grow.':'ကြီးထွားရန် နေရာ။','Take a look around our counselling rooms, classrooms and study spaces in Yangon.':'ရန်ကုန်ရှိ ကျွန်ုပ်တို့၏ အတိုင်ပင်ခံခန်းများ၊ စာသင်ခန်းများနှင့် စာလေ့လာရာနေရာများကို လှည့်လည်ကြည့်ရှုပါ။',
    'Choose a photo':'ဓာတ်ပုံ ရွေးရန်','Office and classroom photos':'ရုံးခန်းနှင့် စာသင်ခန်း ဓာတ်ပုံများ','Previous photo':'ယခင်ဓာတ်ပုံ','Next photo':'နောက်ဓာတ်ပုံ',
    'OUR NETWORK':'ကျွန်ုပ်တို့၏ ကွန်ရက်','Partners across borders.':'နယ်စပ်ကျော် မိတ်ဖက်များ။','Opportunities without limits.':'အကန့်အသတ်မရှိ အခွင့်အလမ်းများ။',
    'Go Go Hankuk is continuously expanding its international network to create broader opportunities for students.':'Go Go Hankuk သည် ကျောင်းသားများအတွက် ပိုမိုကျယ်ပြန့်သော အခွင့်အလမ်းများ ဖန်တီးရန် ၎င်း၏ နိုင်ငံတကာကွန်ရက်ကို အဆက်မပြတ် တိုးချဲ့လျက်ရှိပါသည်။',
    'The network includes universities, colleges, language institutions, and education partners working collaboratively to provide diverse and flexible study options.':'ကွန်ရက်တွင် တက္ကသိုလ်များ၊ ကောလိပ်များ၊ ဘာသာစကားသင်တန်းကျောင်းများနှင့် မတူကွဲပြားပြီး ပြောင်းလွယ်ပြင်လွယ်ရှိသော ပညာသင်ရွေးချယ်စရာများ ပေးအပ်ရန် ပူးပေါင်းဆောင်ရွက်နေသော ပညာရေးမိတ်ဖက်များ ပါဝင်ပါသည်။',
    'A little guidance.':'လမ်းညွှန်မှုအနည်းငယ်။','A whole new horizon.':'လုံးဝအသစ်သော မိုးကုပ်စက်ဝိုင်း။','YOUR GOALS. OUR SHARED JOURNEY.':'သင့်ပန်းတိုင်များ။ ကျွန်ုပ်တို့၏ အတူတကွခရီး။','Big decisions.':'ကြီးမားသော ဆုံးဖြတ်ချက်များ။','A team on your side.':'သင့်ဘက်မှ ရပ်တည်သော အဖွဲ့။',
    'There’s a lot to think about when you plan your education. We help you turn the questions into a clear next step.':'သင့်ပညာရေးကို စီစဉ်သောအခါ စဉ်းစားစရာများစွာ ရှိပါသည်။ မေးခွန်းများကို ရှင်းလင်းသော နောက်တစ်ဆင့်အဖြစ် ပြောင်းလဲနိုင်ရန် ကျွန်ုပ်တို့ ကူညီပေးပါသည်။','Get to know your options':'သင့်ရွေးချယ်စရာများကို လေ့လာပါ',
    // Programs page
    'FIND YOUR DIRECTION':'သင့်လမ်းကြောင်းကို ရှာပါ','Our Programs':'ကျွန်ုပ်တို့၏ အစီအစဉ်များ',
    'From Korean language courses to degree and international pathway programs, choose the route that fits your goals. Select a program to read more about the visa, requirements and how we support you.':'ကိုရီးယားဘာသာစကားသင်တန်းများမှ ဘွဲ့နှင့် နိုင်ငံတကာလမ်းကြောင်း အစီအစဉ်များအထိ သင့်ပန်းတိုင်နှင့် ကိုက်ညီသော လမ်းကြောင်းကို ရွေးချယ်ပါ။ ဗီဇာ၊ လိုအပ်ချက်များနှင့် ကျွန်ုပ်တို့ မည်သို့ပံ့ပိုးသည်ကို ပိုမိုသိရှိရန် အစီအစဉ်တစ်ခုကို ရွေးချယ်ပါ။',
    'FIND YOUR PATHWAY':'သင့်လမ်းကြောင်းကို ရှာပါ','Search programs…':'အစီအစဉ်များ ရှာရန်…','No programs found. Try Korean, bachelor or visa.':'အစီအစဉ် မတွေ့ပါ။ ကိုရီးယား၊ ဘွဲ့ သို့မဟုတ် ဗီဇာဟု ရှာကြည့်ပါ။',
    // News
    'THE GO GO JOURNAL':'GO GO ဂျာနယ်','A little inspiration.':'စိတ်အားထက်သန်မှုအနည်းငယ်။','Ahead of your next move.':'သင့်နောက်တစ်လှမ်း မတိုင်မီ။','Practical ideas and conversations to help you feel ready for what’s next.':'နောက်ဘာလာမည်အတွက် အဆင်သင့်ဖြစ်စေရန် လက်တွေ့ကျသော အကြံဉာဏ်များနှင့် ဆွေးနွေးမှုများ။',
    'News pagination':'သတင်းစာမျက်နှာ ခွဲခြင်း','← Previous':'← ယခင်','Next →':'နောက် →','Page {a} of {b}':'စာမျက်နှာ {a} / {b}','News will be published here soon.':'သတင်းများကို ဤနေရာတွင် မကြာမီ ထုတ်ဝေပါမည်။',
    '← Back to News':'← သတင်းသို့ ပြန်သွားရန်','Article not found':'ဆောင်းပါး မတွေ့ပါ','This article is unavailable. Browse the news list for current stories.':'ဤဆောင်းပါး မရရှိနိုင်ပါ။ လက်ရှိသတင်းများအတွက် သတင်းစာရင်းကို ကြည့်ပါ။','This article is currently available in English only.':'ဤဆောင်းပါးကို လောလောဆယ် အင်္ဂလိပ်ဘာသာဖြင့်သာ ရရှိနိုင်ပါသည်။',
    // Success
    'THE NEXT CHAPTER':'နောက်ထပ်အခန်းကဏ္ဍ','Small steps.':'သေးငယ်သော ခြေလှမ်းများ။','Life-changing journeys.':'ဘဝပြောင်းလဲစေသော ခရီးများ။','Every student’s path is different. Here’s how thoughtful preparation can make a difference.':'ကျောင်းသားတိုင်း၏ လမ်းကြောင်းသည် ကွဲပြားပါသည်။ စေ့စေ့စပ်စပ် ပြင်ဆင်မှုက မည်သို့ ကွာခြားမှုဖြစ်စေနိုင်သည်ကို ကြည့်ပါ။',
    'It starts with':'အခွင့်အလမ်းတစ်ခုဖြင့်','a possibility.':'စတင်ပါသည်။','AND GROWS INTO A PLAN. ↗':'ထို့နောက် အစီအစဉ်တစ်ခုအဖြစ် ကြီးထွားလာသည်။ ↗','ILLUSTRATIVE STUDENT JOURNEY':'နမူနာ ကျောင်းသားခရီးလမ်း','Sample story for this preview, not a verified testimonial.':'ဤနမူနာအတွက် ဥပမာဇာတ်လမ်းဖြစ်ပြီး အတည်ပြုထားသော သက်သေခံချက် မဟုတ်ပါ။','Previous story':'ယခင်ဇာတ်လမ်း','Next story':'နောက်ဇာတ်လမ်း',
    // Admissions
    'Your next chapter starts with a clear plan.':'သင့်နောက်ထပ်အခန်းကဏ္ဍသည် ရှင်းလင်းသော အစီအစဉ်ဖြင့် စတင်ပါသည်။','01 Explore your options':'၀၁ သင့်ရွေးချယ်စရာများကို လေ့လာပါ','Choose a program around your interests, academic background and budget.':'သင့်စိတ်ဝင်စားမှု၊ ပညာရေးနောက်ခံနှင့် ဘတ်ဂျက်နှင့် ကိုက်ညီသော အစီအစဉ်တစ်ခုကို ရွေးချယ်ပါ။',
    '02 Prepare your application':'၀၂ သင့်လျှောက်လွှာကို ပြင်ဆင်ပါ','Confirm the institution’s requirements and gather your documents.':'အဖွဲ့အစည်း၏ လိုအပ်ချက်များကို အတည်ပြုပြီး သင့်စာရွက်စာတမ်းများကို စုဆောင်းပါ။','03 Plan your next step':'၀၃ သင့်နောက်တစ်ဆင့်ကို စီစဉ်ပါ','Review your offer, study costs and arrival arrangements with an advisor.':'သင့်ဝင်ခွင့်၊ ပညာသင်ကုန်ကျစရိတ်နှင့် ရောက်ရှိမှုစီစဉ်ချက်များကို အကြံပေးနှင့် ပြန်လည်သုံးသပ်ပါ။',
    'Ready to begin?':'စတင်ရန် အဆင်သင့်ဖြစ်ပြီလား။','Visit FQ&A for common questions.':'အမေးများသော မေးခွန်းများအတွက် FQ&A ကို ကြည့်ပါ။','Start a conversation ↗':'ဆွေးနွေးမှု စတင်ရန် ↗',
    // FAQ
    'Questions about your education journey':'သင့်ပညာရေးခရီးလမ်းအကြောင်း မေးခွန်းများ','How do I choose a program?':'အစီအစဉ်ကို ဘယ်လိုရွေးချယ်ရမလဲ။','Start with your goals, previous studies and budget. Compare the options on our':'သင့်ပန်းတိုင်များ၊ ယခင်ပညာသင်ကြားမှုနှင့် ဘတ်ဂျက်ဖြင့် စတင်ပါ။ ရွေးချယ်စရာများကို ကျွန်ုပ်တို့၏','Programs page':'အစီအစဉ်များ စာမျက်နှာ','.':'တွင် နှိုင်းယှဉ်ကြည့်ပါ။',
    'What documents do I need?':'ဘယ်စာရွက်စာတမ်းတွေ လိုအပ်မလဲ။','Requirements depend on the institution and program. Confirm the official checklist before applying.':'လိုအပ်ချက်များသည် အဖွဲ့အစည်းနှင့် အစီအစဉ်ပေါ် မူတည်ပါသည်။ မလျှောက်ထားမီ တရားဝင်စာရင်းကို အတည်ပြုပါ။',
    'Are admission or scholarship outcomes guaranteed?':'ဝင်ခွင့် သို့မဟုတ် ပညာသင်ဆု ရလဒ်များကို အာမခံပါသလား။','No. Institutions make their own decisions and apply their own eligibility criteria.':'မဟုတ်ပါ။ အဖွဲ့အစည်းများသည် ၎င်းတို့၏ ကိုယ်ပိုင်ဆုံးဖြတ်ချက်များ ချမှတ်ပြီး ၎င်းတို့၏ အရည်အချင်းသတ်မှတ်ချက်များကို ကျင့်သုံးပါသည်။',
    'How can I speak to an advisor?':'အကြံပေးနှင့် ဘယ်လိုဆွေးနွေးနိုင်မလဲ။','Visit':'ဆွေးနွေးမှု စတင်ရန်','to start a conversation. Agency contact details will be added before launch.':'စာမျက်နှာသို့ သွားပါ။ အေဂျင်စီ ဆက်သွယ်ရန် အချက်အလက်များကို မစတင်မီ ထည့်သွင်းပါမည်။',
    // Portal
    'STUDENT PORTAL':'ကျောင်းသားပေါ်တယ်','Follow your journey,':'သင့်ခရီးလမ်းကို','step by step.':'အဆင့်ဆင့် လိုက်ကြည့်ပါ။',
    'Sign in to see where your application stands — program selection, admission, visa documents, appointment dates and notes from your advisor — all in one place.':'သင့်လျှောက်လွှာ အခြေအနေ — အစီအစဉ်ရွေးချယ်မှု၊ ဝင်ခွင့်၊ ဗီဇာစာရွက်စာတမ်းများ၊ ချိန်းဆိုရက်စွဲများနှင့် အကြံပေး၏ မှတ်ချက်များ — အားလုံးကို တစ်နေရာတည်းတွင် ကြည့်ရှုရန် ဝင်ရောက်ပါ။',
    'Continue with Facebook':'Facebook ဖြင့် ဆက်လက်ရန်','Continue with Google':'Google ဖြင့် ဆက်လက်ရန်',
    'By signing in you agree that Go Go Hankuk may keep your application progress on file for you and your advisor. We only receive your name, email and profile photo.':'ဝင်ရောက်ခြင်းဖြင့် Go Go Hankuk သည် သင်နှင့် သင့်အကြံပေးအတွက် သင့်လျှောက်လွှာတိုးတက်မှုကို မှတ်တမ်းတင်ထားနိုင်သည်ကို သဘောတူပါသည်။ သင့်အမည်၊ အီးမေးလ်နှင့် ပရိုဖိုင်ဓာတ်ပုံကိုသာ ကျွန်ုပ်တို့ ရရှိပါသည်။',
    'Preview mode.':'နမူနာမုဒ်။','The portal is not connected to Firebase yet, so sign-in is disabled. Follow the steps in':'ပေါ်တယ်ကို Firebase နှင့် မချိတ်ဆက်ရသေးသောကြောင့် ဝင်ရောက်ခြင်းကို ပိတ်ထားပါသည်။ အောက်ပါဖိုင်ရှိ အဆင့်များကို လိုက်နာပါ','to activate it, or':'ဖွင့်ရန်၊ သို့မဟုတ်','preview the student view':'ကျောင်းသားမြင်ကွင်းကို နမူနာကြည့်ရန်','preview the staff view':'ဝန်ထမ်းမြင်ကွင်းကို နမူနာကြည့်ရန်','with sample data.':'နမူနာဒေတာဖြင့်။',
    'YOUR PROGRESS':'သင့်တိုးတက်မှု','Admission letter received':'ဝင်ခွင့်စာ လက်ခံရရှိပြီ','Next: visa documents':'နောက်တစ်ဆင့် - ဗီဇာစာရွက်စာတမ်းများ','VISA · D-4-1':'ဗီဇာ · D-4-1','Preparing documents':'စာရွက်စာတမ်းများ ပြင်ဆင်နေသည်','ADVISOR NOTE':'အကြံပေး မှတ်ချက်','“Bank statement approved — well done!”':'“ဘဏ်စာရင်းရှင်းတမ်း အတည်ပြုပြီ — ကောင်းပါသည်။”',
    'Loading your portal…':'သင့်ပေါ်တယ်ကို ဖွင့်နေသည်…','Message my advisor ↗':'အကြံပေးထံ စာပို့ရန် ↗','Sign out':'ထွက်ရန်','APPLICATION PROGRESS':'လျှောက်လွှာ တိုးတက်မှု','Your journey':'သင့်ခရီးလမ်း',
    'PROGRAM':'အစီအစဉ်','Not selected yet':'မရွေးချယ်ရသေးပါ','Intake':'ဝင်ခွင့်ကာလ','Institution':'အဖွဲ့အစည်း','Advisor':'အကြံပေး','VISA STATUS':'ဗီဇာ အခြေအနေ','Not started':'မစတင်ရသေးပါ','Appointment':'ချိန်းဆိုမှု','Submitted on':'တင်သွင်းသည့်ရက်',
    'DOCUMENT CHECKLIST':'စာရွက်စာတမ်း စစ်ဆေးစာရင်း','Your documents':'သင့်စာရွက်စာတမ်းများ','NOTES FROM YOUR ADVISOR':'သင့်အကြံပေး၏ မှတ်ချက်များ','Updates':'အပ်ဒိတ်များ',
    'STAFF DASHBOARD':'ဝန်ထမ်း ဒက်ရှ်ဘုတ်','Students':'ကျောင်းသားများ','Progress':'တိုးတက်မှု','Current stage':'လက်ရှိအဆင့်','Program':'အစီအစဉ်','Visa':'ဗီဇာ','Visa type':'ဗီဇာအမျိုးအစား','Status':'အခြေအနေ','Submitted':'တင်သွင်းပြီး','Approved':'အတည်ပြုပြီး','Rejected':'ငြင်းပယ်ခံရသည်','Other':'အခြား',
    'Appointment (VFS / embassy)':'ချိန်းဆိုမှု (VFS / သံရုံး)','Note to student':'ကျောင်းသားထံ မှတ်ချက်','Documents':'စာရွက်စာတမ်းများ','Add':'ထည့်ရန်','Notes':'မှတ်ချက်များ','Save changes':'ပြောင်းလဲမှုများ သိမ်းရန်',
    'Select a student to view and update their progress.':'ကျောင်းသားတစ်ဦး၏ တိုးတက်မှုကို ကြည့်ရှုပြီး အပ်ဒိတ်လုပ်ရန် ရွေးချယ်ပါ။','Students appear here after they sign in to the portal for the first time.':'ကျောင်းသားများသည် ပေါ်တယ်သို့ ပထမဆုံးအကြိမ် ဝင်ရောက်ပြီးနောက် ဤနေရာတွင် ပေါ်လာပါမည်။','Search students…':'ကျောင်းသားများ ရှာရန်…','Search students':'ကျောင်းသားများ ရှာရန်','Add a document…':'စာရွက်စာတမ်း ထည့်ရန်…','Write an update for the student…':'ကျောင်းသားအတွက် အပ်ဒိတ် ရေးရန်…',
    'Hello, {name}':'မင်္ဂလာပါ {name}','You are at step {a} of {b}: {stage}. Next up: {next}.':'သင်သည် အဆင့် {b} ဆင့်အနက် {a} တွင် ရှိပါသည် — {stage}။ နောက်တစ်ဆင့် — {next}။','Congratulations — you have completed every step of your journey with us.':'ဂုဏ်ယူပါသည် — ကျွန်ုပ်တို့နှင့်အတူ သင့်ခရီးလမ်း၏ အဆင့်တိုင်းကို ပြီးမြောက်ခဲ့ပါပြီ။',
    '{a} of {b} received':'{b} ခုအနက် {a} ခု လက်ခံရရှိပြီ','Last updated {date}':'နောက်ဆုံး အပ်ဒိတ် {date}','Your Go Go Hankuk advisor':'သင့် Go Go Hankuk အကြံပေး','Visa not assigned yet':'ဗီဇာ မသတ်မှတ်ရသေးပါ',
    'Your advisor will add your document checklist soon.':'သင့်အကြံပေးက သင့်စာရွက်စာတမ်းစစ်ဆေးစာရင်းကို မကြာမီ ထည့်သွင်းပါမည်။','No updates yet — your advisor will post notes here as your application moves forward.':'အပ်ဒိတ် မရှိသေးပါ — သင့်လျှောက်လွှာ ရှေ့ဆက်သည်နှင့်အမျှ သင့်အကြံပေးက ဤနေရာတွင် မှတ်ချက်များ တင်ပါမည်။',
    'Initial consultation':'ကနဦး ဆွေးနွေးတိုင်ပင်မှု','We learn about your goals, background and budget.':'သင့်ပန်းတိုင်၊ နောက်ခံနှင့် ဘတ်ဂျက်ကို လေ့လာပါသည်။','Program selected':'အစီအစဉ် ရွေးချယ်ပြီး','Institution and intake confirmed with your advisor.':'အဖွဲ့အစည်းနှင့် ဝင်ခွင့်ကာလကို အကြံပေးနှင့် အတည်ပြုပြီး။',
    'Application submitted':'လျှောက်လွှာ တင်သွင်းပြီး','Documents sent to the institution.':'စာရွက်စာတမ်းများကို အဖွဲ့အစည်းသို့ ပေးပို့ပြီး။','Certificate of Admission (CoA) issued.':'ဝင်ခွင့်လက်မှတ် (CoA) ထုတ်ပေးပြီး။','Visa documents prepared':'ဗီဇာစာရွက်စာတမ်းများ ပြင်ဆင်ပြီး','Financial proof, forms and photos checked.':'ငွေကြေးအထောက်အထား၊ ဖောင်များနှင့် ဓာတ်ပုံများ စစ်ဆေးပြီး။',
    'Visa application submitted':'ဗီဇာလျှောက်လွှာ တင်သွင်းပြီး','Biometrics taken at VFS / embassy.':'VFS / သံရုံးတွင် ဇီဝမက်ထရစ် ယူပြီး။','Visa approved':'ဗီဇာ အတည်ပြုပြီ','Passport returned with visa.':'ဗီဇာနှင့်အတူ နိုင်ငံကူးလက်မှတ် ပြန်ရရှိပြီ။','Pre-departure briefing':'ထွက်ခွာမီ ရှင်းလင်းပွဲ','Flights, accommodation and arrival plan.':'လေယာဉ်လက်မှတ်၊ နေထိုင်ရေးနှင့် ရောက်ရှိမှု အစီအစဉ်။','Arrived & enrolled':'ရောက်ရှိပြီး ကျောင်းအပ်ပြီ','Welcome to your new chapter!':'သင့်အခန်းကဏ္ဍသစ်သို့ ကြိုဆိုပါသည်။',
    'Missing':'မရှိသေးပါ','Under review':'စိစစ်နေသည်','Received':'လက်ခံရရှိပြီ','Needs attention':'ဂရုပြုရန် လိုအပ်သည်'
  },
  content: {
    hero: { title:'ကိုရီးယားတွင် ပညာသင်ကြားပါ', description:'သင့်အနာဂတ်သည်<br>Go Go Education မှ စတင်သည်' },
    contact: { note:'နမူနာဝက်ဘ်ဆိုက် · အေဂျင်စီ ဆက်သွယ်ရန် အချက်အလက်များ ထည့်သွင်းရန်' },
    programs: [
      { tag:'ကိုရီးယားဘာသာစကား', title:'ကိုရီးယားဘာသာစကား အစီအစဉ်', visa:'D-4-1 ဗီဇာ', meta:'တက္ကသိုလ်ဘာသာစကားသင်တန်းကျောင်းများ · ၆ လမှ ၂ နှစ်', description:'တက္ကသိုလ်ဘာသာစကားသင်တန်းကျောင်းတွင် ကိုရီးယားဘာသာစကားကို သင်ယူပြီး ကိုရီးယားတွင် ဘွဲ့သင်ကြားရန် သို့မဟုတ် အလုပ်လုပ်ရန် အခြေခံကို တည်ဆောက်ပါ။',
        details:'D-4-1 (အထွေထွေလေ့ကျင့်သူ) ဗီဇာသည် တက္ကသိုလ်နှင့်ဆက်စပ်သော ဘာသာစကားသင်တန်းကျောင်းတွင် ကိုရီးယားဘာသာစကားသင်တန်း တက်ရောက်နေသော ကျောင်းသားများအတွက် ဖြစ်ပါသည်။ သင်တန်းများကို အခြေခံမှ အဆင့်မြင့်အထိ အဆင့် ၆ ဆင့်ဖြင့် ၁၀ ပတ်စာ သင်တန်းကာလများအဖြစ် စီစဉ်ထားပြီး စကားပြော၊ နားထောင်၊ ဖတ်နှင့် ရေးသားခြင်း အတန်းများ ပါဝင်ပါသည်။\n\nတက္ကသိုလ်အများစုသည် ဝင်ခွင့်အတွက် TOPIK ရလဒ် သို့မဟုတ် ဘာသာစကားသင်တန်းကျောင်းအဆင့် ပြီးမြောက်မှုကို လက်ခံသောကြောင့် ကိုရီးယားတွင် ဘွဲ့ကြို သို့မဟုတ် မဟာဘွဲ့ ဆက်လက်သင်ကြားရန် စီစဉ်သော ကျောင်းသားများအတွက် ဤသည်မှာ အသုံးအများဆုံး ပထမခြေလှမ်းဖြစ်ပါသည်။ သတ်မှတ်ကာလ ပညာသင်ကြားပြီးနောက် ကျောင်းသားများသည် အချိန်ပိုင်းအလုပ်ခွင့်ပြုချက်ကိုလည်း လျှောက်ထားနိုင်ပါသည်။\n\nကျွန်ုပ်တို့၏ အကြံပေးများသည် သင်တန်းကျောင်းရွေးချယ်ရန်၊ ဝင်ခွင့်နှင့် ဗီဇာစာရွက်စာတမ်းများ ပြင်ဆင်ရန်နှင့် နေထိုင်ရေးနှင့် ရောက်ရှိမှုကို စီစဉ်ရန် ကူညီပေးပါသည်။ ကျောင်းလခ၊ ဝင်ခွင့်ရက်စွဲများနှင့် လိုအပ်ချက်များသည် သင်တန်းကျောင်းအလိုက် ကွဲပြားပြီး သင့်ဆွေးနွေးတိုင်ပင်မှုအတွင်း အတည်ပြုပေးပါမည်။' },
      { tag:'အင်္ဂလိပ်ဘာသာစကား', title:'အင်္ဂလိပ်ဘာသာစကား အစီအစဉ်', visa:'D-4-7 ဗီဇာ', meta:'ကိုရီးယားတွင် နိုင်ငံခြားဘာသာစကား လေ့ကျင့်ရေး', description:'ကိုရီးယားကျောင်းဝင်းဘဝကို ခံစားရင်း နိုင်ငံခြားဘာသာစကားလေ့ကျင့်ရေး အစီအစဉ်မှတစ်ဆင့် ကိုရီးယားတွင် အင်္ဂလိပ်စာ သင်ယူပါ။',
        details:'D-4-7 (နိုင်ငံခြားဘာသာစကား လေ့ကျင့်သူ) ဗီဇာကို ကိုရီးယားရှိ အသိအမှတ်ပြုအဖွဲ့အစည်းတစ်ခုတွင် အင်္ဂလိပ်စာကဲ့သို့ နိုင်ငံခြားဘာသာစကားသင်တန်း တက်ရောက်သော ကျောင်းသားများအား ထုတ်ပေးပါသည်။ ကိုရီးယားကျောင်းဝင်းတွင် နေထိုင်ပညာသင်ကြားရင်း နိုင်ငံတကာပတ်ဝန်းကျင်တွင် သင့်အင်္ဂလိပ်စာကို တိုးတက်စေနိုင်ပါသည်။\n\nဤအစီအစဉ်သည် ကိုရီးယား သို့မဟုတ် အခြားနိုင်ငံတွင် အင်္ဂလိပ်ဘာသာဖြင့် သင်ကြားသော ဘွဲ့သို့ မသွားမီ ပညာရေးဆိုင်ရာ အင်္ဂလိပ်စာကို အားဖြည့်လိုသော သို့မဟုတ် အင်္ဂလိပ်စာသင်ယူမှုကို ကိုရီးယားယဉ်ကျေးမှုအတွေ့အကြုံနှင့် ပေါင်းစပ်လိုသော ကျောင်းသားများနှင့် သင့်တော်ပါသည်။\n\nအဖွဲ့အစည်းရွေးချယ်ခြင်း၊ စာရင်းသွင်းခြင်း၊ ဗီဇာလျှောက်ထားခြင်းနှင့် ထွက်ခွာမီ ပြင်ဆင်ခြင်းတို့တွင် ကျွန်ုပ်တို့ လမ်းညွှန်ပေးပါသည်။ သင်တန်းကာလ၊ ကုန်ကျစရိတ်နှင့် ဝင်ခွင့်လိုအပ်ချက်များကို အဖွဲ့အစည်းနှင့် အတည်ပြုပါမည်။' },
      { tag:'ဘွဲ့ကြို', title:'ဘွဲ့ကြို အစီအစဉ်', visa:'D-2-2 ဗီဇာ', meta:'၄ နှစ် ဘွဲ့ · ကိုရီးယား သို့မဟုတ် အင်္ဂလိပ်ဘာသာဖြင့် သင်ကြားသည်', description:'ကိုရီးယားတက္ကသိုလ်တစ်ခုတွင် ကိုရီးယား သို့မဟုတ် အင်္ဂလိပ်ဘာသာဖြင့် သင်ကြားသော အဓိကဘာသာရပ်များဖြင့် ဘွဲ့ကြိုဘွဲ့ ရယူပါ။',
        details:'D-2-2 ဗီဇာသည် ကိုရီးယားတက္ကသိုလ်တစ်ခုတွင် အချိန်ပြည့် ဘွဲ့ကြိုသင်ကြားမှုအတွက် ဖြစ်ပါသည်။ အစီအစဉ်များသည် ယေဘုယျအားဖြင့် လေးနှစ်ကြာပြီး စီးပွားရေး၊ အင်ဂျင်နီယာ၊ IT၊ ဒီဇိုင်း၊ ဧည့်ဝတ်ကျေပွန်ရေးနှင့် ဝိဇ္ဇာဘာသာရပ်များ အပါအဝင် ကျယ်ပြန့်သော အဓိကဘာသာရပ်များဖြင့် ရရှိနိုင်ပါသည်။ တက္ကသိုလ်များစွာသည် ကိုရီးယားဘာသာစကားဖြင့် သင်ကြားသော အစီအစဉ်များနှင့်အတူ အင်္ဂလိပ်ဘာသာဖြင့် သင်ကြားသော လမ်းကြောင်းများကိုလည်း ပေးအပ်ပါသည်။\n\nဝင်ခွင့်အတွက် အထက်တန်းပြီးမြောက်မှု၊ သင်ကြားသည့်ဘာသာစကားပေါ်မူတည်၍ TOPIK သို့မဟုတ် အင်္ဂလိပ်ဘာသာစကား ကျွမ်းကျင်မှုရလဒ်နှင့် အမှတ်စာရင်း၊ ပညာသင်အစီအစဉ်နှင့် ငွေကြေးအထောက်အထား ကဲ့သို့သော ပံ့ပိုးစာရွက်စာတမ်းများ လိုအပ်လေ့ရှိပါသည်။ ဘာသာစကားစွမ်းရည် သို့မဟုတ် ပညာရေးရလဒ်အပေါ် အခြေခံသော ပညာသင်ဆုများ အများအပြားရှိပါသည်။\n\nကျွန်ုပ်တို့အဖွဲ့သည် တက္ကသိုလ်များကို စာရင်းပြုစုရန်၊ ခိုင်မာသော လျှောက်လွှာနှင့် ပညာသင်အစီအစဉ်ကို ပြင်ဆင်ရန်နှင့် ဗီဇာလုပ်ငန်းစဉ်ကို အစမှအဆုံး စီမံရန် ကူညီပေးပါသည်။ လိုအပ်ချက်များနှင့် ကျောင်းလခသည် တက္ကသိုလ်အလိုက် ကွဲပြားပြီး ဆွေးနွေးတိုင်ပင်မှုအတွင်း အတည်ပြုပေးပါမည်။' },
      { tag:'ကောလိပ် ဒီပလိုမာ', title:'၂ နှစ် ကောလိပ် အစီအစဉ်', visa:'D-2-1 ဗီဇာ', meta:'အသောစီရိတ်ဘွဲ့ · လက်တွေ့ကျပြီး အသက်မွေးဝမ်းကျောင်းဗဟိုပြု သင်ကြားမှု', description:'လုပ်ငန်းခွင်ချိတ်ဆက်မှု ခိုင်မာသော ကိုရီးယားကောလိပ်တစ်ခုတွင် လက်တွေ့ကျသော နှစ်နှစ်တာ အသောစီရိတ်ဘွဲ့ကို ပြီးမြောက်ပါ။',
        details:'D-2-1 ဗီဇာသည် ပုံမှန်အားဖြင့် နှစ်နှစ်မှ သုံးနှစ်ကြာသော အသောစီရိတ် (junior college) ဘွဲ့သင်ကြားမှုအတွက် ဖြစ်ပါသည်။ ကိုရီးယားကောလိပ်များသည် ဟိုတယ်စီမံခန့်ခွဲမှု၊ ချက်ပြုတ်အနုပညာ၊ အလှအပ၊ မော်တော်ယာဉ်၊ IT၊ သူနာပြုပံ့ပိုးမှု၊ ခရီးသွားလုပ်ငန်းနှင့် စီးပွားရေးကဲ့သို့သော နယ်ပယ်များတွင် လက်တွေ့ကျပြီး အသက်မွေးဝမ်းကျောင်းဦးတည်သော လေ့ကျင့်မှုကို အဓိကထားပါသည်။\n\nဤအစီအစဉ်များသည် ရှင်းလင်းသော အလုပ်အကိုင်လမ်းကြောင်းများပါသော ပိုမိုတိုတောင်းပြီး ကျွမ်းကျင်မှုဗဟိုပြု အရည်အချင်းကို လိုချင်သော သို့မဟုတ် နောက်ပိုင်းတွင် ဘွဲ့ကြိုဘွဲ့သို့ ပြောင်းရွှေ့ရန် စီစဉ်သော ကျောင်းသားများအတွက် ရေပန်းစားသော လမ်းကြောင်းဖြစ်ပါသည်။\n\nကောလိပ်များနှင့် အဓိကဘာသာရပ်များကို နှိုင်းယှဉ်ရန်၊ ဘာသာစကားနှင့် စာရွက်စာတမ်းလိုအပ်ချက်များ ပြည့်မီရန်နှင့် ဝင်ခွင့်နှင့် ဗီဇာအဆင့်များ ပြီးမြောက်ရန် ကျွန်ုပ်တို့ ကူညီပေးပါသည်။ ကျောင်းလခ၊ ဝင်ခွင့်ရက်စွဲများနှင့် အရည်အချင်းသတ်မှတ်ချက်များသည် ကောလိပ်အလိုက် ကွဲပြားပါသည်။' },
      { tag:'ဘွဲ့လွန်', title:'မဟာဘွဲ့ အစီအစဉ်', visa:'D-2-3 ဗီဇာ', meta:'မဟာဘွဲ့ · သုတေသနနှင့် သင်တန်းအခြေပြု အစီအစဉ်များ', description:'ကိုရီးယားဘွဲ့လွန်ကျောင်းမှ မဟာဘွဲ့ဖြင့် သင့်အသက်မွေးဝမ်းကျောင်းကို မြှင့်တင်ပါ။',
        details:'D-2-3 ဗီဇာသည် ကိုရီးယားဘွဲ့လွန်ကျောင်းတစ်ခုတွင် မဟာဘွဲ့သင်ကြားမှုအတွက် ဖြစ်ပါသည်။ အစီအစဉ်များသည် ပုံမှန်အားဖြင့် နှစ်နှစ်ကြာပြီး စီးပွားရေး၊ အင်ဂျင်နီယာ၊ သိပ္ပံ၊ ပညာရေး၊ နိုင်ငံတကာလေ့လာမှုနှင့် အခြားဘာသာရပ်များတွင် ကိုရီးယားနှင့် အင်္ဂလိပ်ဘာသာစကား နှစ်မျိုးလုံးဖြင့် ရရှိနိုင်ပါသည်။\n\nလျှောက်ထားသူများသည် ပုံမှန်အားဖြင့် အသိအမှတ်ပြုဘွဲ့ကြိုဘွဲ့၊ အစီအစဉ်နှင့်သင့်တော်သော ဘာသာစကားကျွမ်းကျင်မှုရလဒ်၊ ပညာရေးဆိုင်ရာ ထောက်ခံစာများနှင့် သုတေသန သို့မဟုတ် ပညာသင်အစီအစဉ် လိုအပ်ပါသည်။ ဘွဲ့လွန်ပညာသင်ဆုများ၊ သုတေသနလက်ထောက်ရာထူးများနှင့် တက္ကသိုလ်ရန်ပုံငွေများကို နိုင်ငံတကာကျောင်းသားများအတွက် မကြာခဏ ရရှိနိုင်ပါသည်။\n\nကျွန်ုပ်တို့၏ အကြံပေးများသည် သင့်တော်သော အစီအစဉ်များနှင့် ကြီးကြပ်သူများကို ရှာဖွေရန်၊ သင့်လျှောက်လွှာနှင့် စာရွက်စာတမ်းများ ပြင်ဆင်ရန်နှင့် ဗီဇာလုပ်ငန်းစဉ်ကို ကိုင်တွယ်ရန် ပံ့ပိုးပေးပါသည်။ လိုအပ်ချက်များနှင့် ရန်ပုံငွေသည် တက္ကသိုလ်အလိုက် ကွဲပြားပါသည်။' },
      { tag:'ဒေသဆိုင်ရာ လမ်းကြောင်း', title:'မက်ထရိုပိုလီတန် ဗီဇာ အစီအစဉ်', visa:'D-2-1 ဗီဇာ', meta:'အသောစီရိတ်ဘွဲ့ · ဆိုးလ်မြို့ပတ်ဝန်းကျင် ကောလိပ်များ', description:'D-2-1 ဗီဇာအမျိုးအစားအောက်တွင် ဆိုးလ်မြို့ပတ်ဝန်းကျင်ရှိ အဖွဲ့အစည်းများကို အဓိကထားသော ကောလိပ်လမ်းကြောင်း။',
        details:'မက်ထရိုပိုလီတန် ဗီဇာ အစီအစဉ်သည် ဆိုးလ်မြို့ပတ်ဝန်းကျင်ရှိ ကောလိပ်များကို အဓိကထားသော D-2-1 အသောစီရိတ်ဘွဲ့ လမ်းကြောင်းဖြစ်ပြီး လက်တွေ့ကျသော နှစ်နှစ်တာ အရည်အချင်းကို ပြီးမြောက်ရင်း မြို့တော်ဒေသ၏ ကျောင်းဝင်းများ၊ အချိန်ပိုင်းအလုပ်အခွင့်အလမ်းများနှင့် အလုပ်ရှင်ကွန်ရက်များကို ကျောင်းသားများ လက်လှမ်းမီစေပါသည်။\n\nဤအစီအစဉ်ကို ရှင်းလင်းပြီး ကောင်းမွန်စွာပံ့ပိုးထားသော ဝင်ခွင့်လုပ်ငန်းစဉ်ဖြင့် ဆိုးလ်အနီးတွင် ပညာသင်ကြားလိုသော ကျောင်းသားများအတွက် ဒီဇိုင်းထုတ်ထားပါသည်။ ရရှိနိုင်သော အဓိကဘာသာရပ်များ၊ ပါဝင်သော ကောလိပ်များနှင့် အခြေအနေများကို ဝင်ခွင့်ကာလတိုင်း အသစ်ပြင်ဆင်ပါသည်။\n\nပါဝင်သော အဖွဲ့အစည်းများ၏ လက်ရှိစာရင်း၊ အရည်အချင်းသတ်မှတ်ချက်များ၊ ကျောင်းလခနှင့် ဝင်ခွင့်ရက်စွဲများအတွက် ကျွန်ုပ်တို့၏ အကြံပေးများနှင့် ဆွေးနွေးပါ။' },
      { tag:'နိုင်ငံတကာ လမ်းကြောင်း', title:'မလေးရှားမှ ကိုရီးယားနှင့် ယူကေ အစီအစဉ်', visa:'လမ်းကြောင်း အစီအစဉ်', meta:'မလေးရှားတွင် အရင်သင်ကြား · ကိုရီးယား သို့မဟုတ် ယူကေသို့ ဆက်လက်', description:'မလေးရှားတွင် သင့်ပညာသင်ကြားမှုကို စတင်ပြီး ကိုရီးယား သို့မဟုတ် ယူနိုက်တက်ကင်းဒမ်းတွင် ဘွဲ့သို့ ဆက်လက်တက်ရောက်ပါ။',
        details:'ဤလမ်းကြောင်းသည် ကျောင်းသားများအား မလေးရှားရှိ မိတ်ဖက်အဖွဲ့အစည်းတစ်ခုတွင် ဖောင်ဒေးရှင်း၊ အင်္ဂလိပ်စာ သို့မဟုတ် ဒီပလိုမာ အစီအစဉ်ဖြင့် စတင်ပြီးနောက် ဘွဲ့ပြီးမြောက်ရန် တောင်ကိုရီးယား သို့မဟုတ် ယူနိုက်တက်ကင်းဒမ်းရှိ တက္ကသိုလ်တစ်ခုသို့ ပြောင်းရွှေ့နိုင်စေပါသည်။\n\nမလေးရှားတွင် စတင်ခြင်းသည် ကနဦးကုန်ကျစရိတ် နည်းပါးခြင်း၊ အင်္ဂလိပ်ဘာသာဖြင့် သင်ကြားခြင်းနှင့် နိုင်ငံတကာပညာသင်ကြားမှုသို့ ပိုမိုချောမွေ့သော ကူးပြောင်းမှုကို ပေးအပ်ပြီး မိတ်ဖက်ဖွဲ့စည်းပုံသည် ပညာရေးနှင့် ဘာသာစကားအခြေအနေများ ပြည့်မီသည်နှင့် ဆက်လက်တက်ရောက်ရန် ရှင်းလင်းသော လမ်းကြောင်းကို ပေးပါသည်။\n\nကျွန်ုပ်တို့အဖွဲ့သည် ရရှိနိုင်သော လမ်းကြောင်းများ၊ ဝင်ခွင့်အခြေအနေများနှင့် စုစုပေါင်း ပညာသင်ကုန်ကျစရိတ်ကို ရှင်းပြပြီး မလေးရှား၊ ကိုရီးယားနှင့် ယူကေရှိ မိတ်ဖက်အဖွဲ့အစည်းများနှင့် သင့်လျှောက်လွှာများကို ညှိနှိုင်းပေးပါသည်။ ဆက်လက်တက်ရောက်ခွင့်သည် အဖွဲ့အစည်းတစ်ခုစီ၏ လိုအပ်ချက်များနှင့် သင့်ရလဒ်များပေါ် မူတည်ပါသည်။' },
      { tag:'နိုင်ငံတကာ လမ်းကြောင်း', title:'ထိုင်းမှ ကိုရီးယား အစီအစဉ်', visa:'လမ်းကြောင်း အစီအစဉ်', meta:'ထိုင်းတွင် အရင်သင်ကြား · ကိုရီးယားသို့ ဆက်လက်', description:'ထိုင်းနိုင်ငံရှိ မိတ်ဖက်အဖွဲ့အစည်းတစ်ခုတွင် သင့်ခရီးကို စတင်ပြီး ကိုရီးယားတက္ကသိုလ်သို့ ဆက်လက်သွားပါ။',
        details:'ထိုင်းမှ ကိုရီးယား အစီအစဉ်သည် အဆင့်နှစ်ဆင့်ပါ လမ်းကြောင်းဖြစ်ပါသည် — ကျောင်းသားများသည် ထိုင်းနိုင်ငံရှိ မိတ်ဖက်အဖွဲ့အစည်းတစ်ခုတွင် ပြင်ဆင်မှု သို့မဟုတ် ဘာသာစကားအစီအစဉ်ကို အရင်ပြီးမြောက်ပြီးနောက် ကိုရီးယားဘာသာစကားသင်တန်းကျောင်း၊ ကောလိပ် သို့မဟုတ် တက္ကသိုလ်သို့ ဆက်လက်တက်ရောက်ပါသည်။\n\nဤလမ်းကြောင်းသည် ကိုရီးယားသို့ ပိုမိုကြီးမားသော ပြောင်းရွှေ့မှုမပြုမီ အနီးအနား၊ ကုန်ကျစရိတ်သက်သာသော နေရာတွင် ဘာသာစကားစွမ်းရည်နှင့် ပညာရေးအဆင်သင့်ဖြစ်မှုကို တည်ဆောက်လိုသော ကျောင်းသားများနှင့် သင့်တော်ပြီး ကူးပြောင်းမှုအဆင့်တိုင်းတွင် လမ်းညွှန်မှုရရှိပါသည်။\n\nကျွန်ုပ်တို့၏ အကြံပေးများသည် လက်ရှိမိတ်ဖက်အဖွဲ့အစည်းများ၊ ဆက်လက်တက်ရောက်ရန် အခြေအနေများနှင့် အဆင့်တစ်ခုစီအတွက် ဗီဇာအဆင့်များကို ရှင်းပြပေးပါသည်။ အသေးစိတ်ကို သင့်ဆွေးနွေးတိုင်ပင်မှုအတွင်း အတည်ပြုပေးပါမည်။' }
    ],
    benefits: [
      { title:'သင့်အတွက် တည်ဆောက်ထားသော လမ်းညွှန်မှု', text:'သင့်စိတ်ဝင်စားမှု၊ သင့်ဘတ်ဂျက်၊ သင့်အရှိန်။ နားထောင်ခြင်းဖြင့် စတင်သော အစီအစဉ်။' },
      { title:'အဆင့်တိုင်းတွင် ရှင်းလင်းမှု', text:'ရှေ့ဆက်မတိုင်မီ သင့်ရွေးချယ်မှုများ၊ စာရွက်စာတမ်းများနှင့် အချိန်ဇယားများကို နားလည်ပါ။' },
      { title:'လျှောက်လွှာထက် ကျော်လွန်သော ပံ့ပိုးမှု', text:'သင်တန်းရွေးချယ်ခြင်းမှ ရောက်ရှိရန် ပြင်ဆင်ခြင်းအထိ နောက်ဘာလာမည်ကို သိရှိပါ။' }
    ],
    stories: [
      { quote:'ရှေ့ရှိ ခြေလှမ်းများကို မြင်လာသောအခါ ကြီးမားသော အိပ်မက်တစ်ခုက ပိုမိုအောင်မြင်နိုင်သည်ဟု ခံစားရပါသည်။', name:'ရွေးချယ်စရာများ လေ့လာခြင်းမှ လျှောက်လွှာပြင်ဆင်ခြင်းအထိ', detail:'နမူနာ ဘွဲ့ကြိုခရီးလမ်း' },
      { quote:'ကျွန်ုပ်စိတ်ဝင်စားမှုနှင့် ပတ်သက်သော သင်တန်းများကို နှိုင်းယှဉ်ခြင်းက ကျွန်ုပ် အမှန်တကယ် သင်ယူလိုသည့်အရာကို မြင်စေခဲ့ပါသည်။', name:'မသေချာမှုမှ ပိုမိုရှင်းလင်းသော လမ်းကြောင်းသို့', detail:'နမူနာ သင်တန်းရွေးချယ်မှု ခရီးလမ်း' },
      { quote:'တည်ငြိမ်သော ပညာသင်အစီအစဉ်က ကျွန်ုပ်၏ အင်္ဂလိပ်စာပြင်ဆင်မှုကို ပိုမိုယုံကြည်မှုဖြင့် ချဉ်းကပ်စေခဲ့ပါသည်။', name:'ပန်းတိုင်အမှတ်မှ အပတ်စဉ် သင်ယူမှုအစီအစဉ်သို့', detail:'နမူနာ ဘာသာစကားသင်ယူမှု ခရီးလမ်း' }
    ],
    office: [
      { caption:'ရန်ကုန်မြို့လယ်ရှိ ကျွန်ုပ်တို့၏ ရုံးအဆောက်အအုံ' },{ caption:'ကျောင်းသား အတိုင်ပင်ခံခန်း' },{ caption:'အစည်းအဝေးခန်း' },{ caption:'စာသင်ခန်း' },
      { caption:'စာလေ့လာခန်း' },{ caption:'ဆွေးနွေးတိုင်ပင်ရာ နေရာ' },{ caption:'အလုပ်လုပ်နေသော ကျွန်ုပ်တို့၏ အကြံပေးအဖွဲ့' },{ caption:'အစီအစဉ်ဆိုင်ရာ အရင်းအမြစ်များနှင့် မိတ်ဖက်စာရွက်စာတမ်းများ' }
    ],
    network: [
      { name:'တောင်ကိုရီးယား', note:'တက္ကသိုလ်များ၊ ဘာသာစကားသင်တန်းများနှင့် လမ်းကြောင်းအစီအစဉ်များ' },
      { name:'မလေးရှား', note:'တက္ကသိုလ်များနှင့် ကောလိပ်များ' },
      { name:'ထိုင်း', note:'တက္ကသိုလ်များနှင့် နိုင်ငံတကာ အစီအစဉ်များ' },
      { name:'အခြား ထွန်းသစ်စ ကမ္ဘာလုံးဆိုင်ရာ ပန်းတိုင်များ', note:'ကမ္ဘာတစ်ဝှမ်း မိတ်ဖက်ဆက်ဆံရေး တိုးချဲ့ခြင်း' }
    ]
  }
},

/* =============================== 한국어 =============================== */
ko: {
  html: {
    aboutUsTitle: '회사 <em>소개</em>'
  },
  ui: {
    'Home':'홈','About':'소개','Programs':'프로그램','News':'뉴스','Success':'성공 사례','Admissions':'입학 안내','FQ&A':'자주 묻는 질문','Portal':'포털',
    'Student Portal':'학생 포털','News article':'뉴스 기사',
    'Skip to content':'본문으로 건너뛰기','Menu ☰':'메뉴 ☰','Search programs':'프로그램 검색','Switch to dark mode':'다크 모드로 전환','Switch to light mode':'라이트 모드로 전환',
    'Go Go Education home':'Go Go Education 홈','Main navigation':'주 메뉴','Close details':'닫기',
    'Opening doors.':'문을 열어드립니다.','Expanding possibilities.':'가능성을 넓혀갑니다.','Explore':'둘러보기','Programs & courses':'프로그램 및 과정','Why choose us':'우리를 선택해야 하는 이유',
    'Stay inspired':'영감 받기','Student journeys':'학생들의 여정','News & events':'뉴스 및 이벤트','Let’s connect':'연락하기','Speak to an advisor ↗':'상담사와 상담하기 ↗','Student portal':'학생 포털',
    'Made for your next chapter.':'당신의 다음 장을 위해 만들었습니다.','Back to top ↑':'맨 위로 ↑','Talk about your next step ↗':'다음 단계 상담하기 ↗',
    'Explore program':'프로그램 보기','Primary destination':'주요 유학지',
    'BIG DREAMS. NEW POSSIBILITIES.':'큰 꿈. 새로운 가능성.','Discover our programs':'프로그램 살펴보기','Talk to an advisor':'상담사와 이야기하기',
    'Est. 2022':'2022년 설립','Yangon, Myanmar':'미얀마 양곤','WHO WE ARE':'회사 소개',
    'Go Go Hankuk Consultancy Company was established in 2022 with the vision of empowering Myanmar students to achieve their academic and career dreams.':'Go Go Hankuk Consultancy Company는 미얀마 학생들이 학업과 진로의 꿈을 이룰 수 있도록 돕겠다는 비전으로 2022년에 설립되었습니다.',
    'Over the past 3 years, we have successfully guided approximately over 700 students, providing them with tailored solutions to navigate educational challenges both in Myanmar and abroad. With over three years of experience, we are committed to continuously improving our services to help youths achieve brighter futures.':'지난 3년 동안 약 700명 이상의 학생들에게 미얀마 국내외의 교육 과제를 해결할 수 있는 맞춤형 솔루션을 제공하며 성공적으로 안내해 왔습니다. 3년 이상의 경험을 바탕으로, 청년들이 더 밝은 미래를 이룰 수 있도록 서비스를 지속적으로 개선해 나가고 있습니다.',
    'Our consultancy addresses the challenges students face in Myanmar while ensuring a smooth transition to peaceful and productive learning experiences abroad. By prioritizing safety and academic success, we ease parents\' concerns and provide unparalleled support. Go Go Hankuk Consultancy Company stands as a trusted leader in educational consultancy, paving the way for future generations.':'저희 컨설팅은 미얀마 학생들이 직면한 과제를 해결하는 동시에 해외에서 평화롭고 생산적인 학습 경험으로 원활하게 전환할 수 있도록 지원합니다. 안전과 학업 성취를 최우선으로 하여 학부모의 걱정을 덜어드리고 비교할 수 없는 지원을 제공합니다. Go Go Hankuk Consultancy Company는 교육 컨설팅 분야에서 신뢰받는 선두 기업으로서 미래 세대를 위한 길을 열어가고 있습니다.',
    'Established':'설립','Students guided':'지도한 학생 수','Years of experience':'년의 경험',
    'VISION':'비전','Our vision':'우리의 비전','To be a leading international education bridge that empowers Myanmar students to access global academic and career opportunities.':'미얀마 학생들이 세계적인 학업 및 진로 기회에 접근할 수 있도록 하는 선도적인 국제 교육 가교가 되는 것.',
    'MISSION':'미션','Our mission':'우리의 미션',
    'To deliver professional, transparent, and student-focused education consulting services':'전문적이고 투명하며 학생 중심의 교육 컨설팅 서비스를 제공합니다',
    'To establish strong and sustainable partnerships with international institutions':'국제 교육기관과 강력하고 지속 가능한 파트너십을 구축합니다',
    'To support students in achieving academic success and long-term career development':'학생들의 학업 성취와 장기적인 진로 개발을 지원합니다',
    'To create accessible global education pathways for future generations':'미래 세대를 위해 접근 가능한 글로벌 교육 경로를 만듭니다',
    'CORE VALUES':'핵심 가치','What we stand for.':'우리가 지키는 가치.','The principles that guide every conversation, application and partnership.':'모든 상담, 지원, 파트너십을 이끄는 원칙입니다.',
    'Integrity':'정직','Upholding honesty and transparency in every process':'모든 과정에서 정직과 투명성을 지킵니다','Trust':'신뢰','Building long-term relationships with students and partners':'학생 및 파트너와 장기적인 관계를 구축합니다',
    'Student Success':'학생의 성공','Prioritizing student outcomes and development':'학생의 성과와 성장을 최우선으로 합니다','Professional Excellence':'전문적 우수성','Maintaining high standards in service delivery':'서비스 제공에서 높은 기준을 유지합니다',
    'Global Collaboration':'글로벌 협력','Strengthening international partnerships and networks':'국제 파트너십과 네트워크를 강화합니다',
    'LEADERSHIP':'리더십','Meet the people':'Go Go Hankuk을 이끄는','behind Go Go Hankuk.':'사람들을 만나보세요.','Experienced advisors dedicated to guiding every student from first enquiry to arrival.':'첫 문의부터 도착까지 모든 학생을 안내하는 데 헌신하는 경험 많은 상담사들입니다.',
    'FOUNDER\'S PROFILE':'설립자 프로필','Zun Phu Wai':'준 푸 웨이','ZUN PHU WAI':'준 푸 웨이','Founder & Managing Director':'설립자 겸 대표이사',
    'Zun Phu Wai is the Founder and Chief Executive Officer of Go Go Hankuk, leading the company’s strategic direction and overall operations.':'준 푸 웨이는 Go Go Hankuk의 설립자이자 최고경영자로서 회사의 전략적 방향과 전반적인 운영을 이끌고 있습니다.',
    'With a background in education consultancy and international program coordination, she has developed strong expertise in student advisory services, visa processing, and partnership development with educational institutions.':'교육 컨설팅과 국제 프로그램 조정 분야의 경력을 바탕으로 학생 상담 서비스, 비자 절차, 교육기관과의 파트너십 개발에서 탄탄한 전문성을 쌓아왔습니다.',
    'Since establishing Go Go Hankuk in 2022, she has played a key role in building the company into a reliable consultancy focused on South Korea and international pathway programs.':'2022년 Go Go Hankuk을 설립한 이후, 한국 및 국제 진학 프로그램에 특화된 신뢰할 수 있는 컨설팅 회사로 성장시키는 데 핵심적인 역할을 해왔습니다.',
    'Her leadership is centered on delivering professional, transparent, and student-focused services, ensuring that every student receives clear guidance and support throughout their study-abroad journey.':'그녀의 리더십은 전문적이고 투명하며 학생 중심의 서비스를 제공하는 데 중점을 두어, 모든 학생이 유학 여정 내내 명확한 안내와 지원을 받을 수 있도록 합니다.',
    'Her vision is to position Go Go Hankuk as a leading Korea and international pathway education consultancy in Southeast Asia.':'그녀의 비전은 Go Go Hankuk을 동남아시아의 선도적인 한국 및 국제 진학 교육 컨설팅 기관으로 자리매김하는 것입니다.',
    'DIRECTOR\'S PROFILE':'이사 프로필','Nay Myo Thura Naing':'네 묘 투라 나잉','NAY MYO THURA NAING':'네 묘 투라 나잉','Director':'이사',
    'Nay Myo Thura Naing serves as the Director of Go Go Hankuk, leading the company’s branding, marketing strategy, and business development initiatives.':'네 묘 투라 나잉은 Go Go Hankuk의 이사로서 회사의 브랜딩, 마케팅 전략, 사업 개발을 이끌고 있습니다.',
    'He holds an MBA (International Program) from Siam University, Thailand, with a focus on marketing, business strategy, and the education industry.':'태국 시암대학교에서 마케팅, 경영 전략, 교육 산업에 중점을 둔 MBA(국제 프로그램) 학위를 취득했습니다.',
    'With nearly 10 years of experience in marketing and graphic design, he brings strong expertise in brand development, visual communication, and digital marketing. His work plays a key role in strengthening Go Go Hankuk’s professional image and positioning in the education consultancy market.':'마케팅과 그래픽 디자인 분야에서 약 10년의 경험을 바탕으로 브랜드 개발, 시각 커뮤니케이션, 디지털 마케팅에서 탄탄한 전문성을 갖추고 있습니다. 그의 업무는 교육 컨설팅 시장에서 Go Go Hankuk의 전문적인 이미지와 입지를 강화하는 데 핵심적인 역할을 합니다.',
    'At Go Go Hankuk, he is responsible for developing communication strategies, supporting business expansion, and enhancing customer experience to ensure consistent growth and brand recognition.':'Go Go Hankuk에서 그는 커뮤니케이션 전략 개발, 사업 확장 지원, 고객 경험 향상을 담당하며 지속적인 성장과 브랜드 인지도를 확보하고 있습니다.',
    'His vision is to build Go Go Hankuk into a premium and internationally recognized education consultancy brand.':'그의 비전은 Go Go Hankuk을 프리미엄의 국제적으로 인정받는 교육 컨설팅 브랜드로 성장시키는 것입니다.',
    'OUR OFFICE & CLASSROOM':'사무실 및 강의실','A place to learn,':'배우고, 계획하고,','plan and grow.':'성장하는 공간.','Take a look around our counselling rooms, classrooms and study spaces in Yangon.':'양곤에 있는 상담실, 강의실, 학습 공간을 둘러보세요.',
    'Choose a photo':'사진 선택','Office and classroom photos':'사무실 및 강의실 사진','Previous photo':'이전 사진','Next photo':'다음 사진',
    'OUR NETWORK':'네트워크','Partners across borders.':'국경을 넘는 파트너.','Opportunities without limits.':'한계 없는 기회.',
    'Go Go Hankuk is continuously expanding its international network to create broader opportunities for students.':'Go Go Hankuk은 학생들에게 더 넓은 기회를 제공하기 위해 국제 네트워크를 지속적으로 확장하고 있습니다.',
    'The network includes universities, colleges, language institutions, and education partners working collaboratively to provide diverse and flexible study options.':'네트워크에는 다양하고 유연한 학습 옵션을 제공하기 위해 협력하는 대학, 칼리지, 어학기관, 교육 파트너가 포함됩니다.',
    'A little guidance.':'작은 안내.','A whole new horizon.':'완전히 새로운 지평.','YOUR GOALS. OUR SHARED JOURNEY.':'당신의 목표. 우리가 함께하는 여정.','Big decisions.':'중요한 결정.','A team on your side.':'당신 편에 선 팀.',
    'There’s a lot to think about when you plan your education. We help you turn the questions into a clear next step.':'교육을 계획할 때는 고려할 것이 많습니다. 저희는 그 질문들을 명확한 다음 단계로 바꿀 수 있도록 도와드립니다.','Get to know your options':'선택지 알아보기',
    'FIND YOUR DIRECTION':'방향 찾기','Our Programs':'프로그램 안내',
    'From Korean language courses to degree and international pathway programs, choose the route that fits your goals. Select a program to read more about the visa, requirements and how we support you.':'한국어 과정부터 학위 및 국제 진학 프로그램까지, 목표에 맞는 경로를 선택하세요. 프로그램을 선택하면 비자, 요건, 지원 방법에 대해 자세히 알아볼 수 있습니다.',
    'FIND YOUR PATHWAY':'진로 찾기','Search programs…':'프로그램 검색…','No programs found. Try Korean, bachelor or visa.':'프로그램을 찾을 수 없습니다. 한국어, 학사, 비자 등으로 검색해 보세요.',
    'THE GO GO JOURNAL':'GO GO 저널','A little inspiration.':'작은 영감.','Ahead of your next move.':'다음 발걸음에 앞서.','Practical ideas and conversations to help you feel ready for what’s next.':'다음 단계를 준비할 수 있도록 돕는 실용적인 아이디어와 이야기.',
    'News pagination':'뉴스 페이지 이동','← Previous':'← 이전','Next →':'다음 →','Page {a} of {b}':'{a} / {b} 페이지','News will be published here soon.':'곧 이곳에 뉴스가 게시됩니다.',
    '← Back to News':'← 뉴스로 돌아가기','Article not found':'기사를 찾을 수 없습니다','This article is unavailable. Browse the news list for current stories.':'이 기사를 볼 수 없습니다. 뉴스 목록에서 최신 소식을 확인하세요.','This article is currently available in English only.':'이 기사는 현재 영어로만 제공됩니다.',
    'THE NEXT CHAPTER':'다음 장','Small steps.':'작은 걸음.','Life-changing journeys.':'인생을 바꾸는 여정.','Every student’s path is different. Here’s how thoughtful preparation can make a difference.':'모든 학생의 길은 다릅니다. 세심한 준비가 어떤 차이를 만드는지 확인해 보세요.',
    'It starts with':'하나의 가능성에서','a possibility.':'시작됩니다.','AND GROWS INTO A PLAN. ↗':'그리고 계획으로 자라납니다. ↗','ILLUSTRATIVE STUDENT JOURNEY':'학생 여정 예시','Sample story for this preview, not a verified testimonial.':'미리보기용 예시 이야기이며 검증된 후기가 아닙니다.','Previous story':'이전 이야기','Next story':'다음 이야기',
    'Your next chapter starts with a clear plan.':'당신의 다음 장은 명확한 계획에서 시작됩니다.','01 Explore your options':'01 선택지 탐색','Choose a program around your interests, academic background and budget.':'관심사, 학력, 예산에 맞는 프로그램을 선택하세요.',
    '02 Prepare your application':'02 지원서 준비','Confirm the institution’s requirements and gather your documents.':'기관의 요건을 확인하고 서류를 준비하세요.','03 Plan your next step':'03 다음 단계 계획','Review your offer, study costs and arrival arrangements with an advisor.':'입학 허가, 학업 비용, 도착 준비를 상담사와 검토하세요.',
    'Ready to begin?':'시작할 준비가 되셨나요?','Visit FQ&A for common questions.':'자주 묻는 질문은 FQ&A를 확인하세요.','Start a conversation ↗':'상담 시작하기 ↗',
    'Questions about your education journey':'교육 여정에 관한 질문','How do I choose a program?':'프로그램은 어떻게 선택하나요?','Start with your goals, previous studies and budget. Compare the options on our':'목표, 이전 학업, 예산에서 시작하세요. 다음 페이지에서 옵션을 비교해 보세요:','Programs page':'프로그램 페이지',
    'What documents do I need?':'어떤 서류가 필요한가요?','Requirements depend on the institution and program. Confirm the official checklist before applying.':'요건은 기관과 프로그램에 따라 다릅니다. 지원 전에 공식 체크리스트를 확인하세요.',
    'Are admission or scholarship outcomes guaranteed?':'입학이나 장학금 결과가 보장되나요?','No. Institutions make their own decisions and apply their own eligibility criteria.':'아니요. 기관은 자체적으로 결정하며 자체 자격 기준을 적용합니다.',
    'How can I speak to an advisor?':'상담사와 어떻게 상담할 수 있나요?','Visit':'상담을 시작하려면','to start a conversation. Agency contact details will be added before launch.':'페이지를 방문하세요. 에이전시 연락처는 출시 전에 추가됩니다.',
    'STUDENT PORTAL':'학생 포털','Follow your journey,':'당신의 여정을','step by step.':'단계별로 확인하세요.',
    'Sign in to see where your application stands — program selection, admission, visa documents, appointment dates and notes from your advisor — all in one place.':'로그인하여 프로그램 선택, 입학, 비자 서류, 예약 일정, 상담사 메모 등 지원 현황을 한곳에서 확인하세요.',
    'Continue with Facebook':'Facebook으로 계속하기','Continue with Google':'Google로 계속하기',
    'By signing in you agree that Go Go Hankuk may keep your application progress on file for you and your advisor. We only receive your name, email and profile photo.':'로그인하면 Go Go Hankuk이 학생과 상담사를 위해 지원 진행 상황을 보관하는 데 동의하는 것입니다. 이름, 이메일, 프로필 사진만 제공받습니다.',
    'Preview mode.':'미리보기 모드.','The portal is not connected to Firebase yet, so sign-in is disabled. Follow the steps in':'포털이 아직 Firebase에 연결되지 않아 로그인이 비활성화되어 있습니다. 다음 파일의 단계를 따르세요:','to activate it, or':'활성화하거나','preview the student view':'학생 화면 미리보기','preview the staff view':'직원 화면 미리보기','with sample data.':'샘플 데이터로.',
    'YOUR PROGRESS':'진행 상황','Admission letter received':'입학 허가서 수령','Next: visa documents':'다음: 비자 서류','VISA · D-4-1':'비자 · D-4-1','Preparing documents':'서류 준비 중','ADVISOR NOTE':'상담사 메모','“Bank statement approved — well done!”':'“은행 잔고증명서 승인 — 잘하셨어요!”',
    'Loading your portal…':'포털을 불러오는 중…','Message my advisor ↗':'상담사에게 메시지 ↗','Sign out':'로그아웃','APPLICATION PROGRESS':'지원 진행 상황','Your journey':'나의 여정',
    'PROGRAM':'프로그램','Not selected yet':'아직 선택되지 않음','Intake':'입학 시기','Institution':'교육기관','Advisor':'상담사','VISA STATUS':'비자 상태','Not started':'시작 전','Appointment':'예약','Submitted on':'제출일',
    'DOCUMENT CHECKLIST':'서류 체크리스트','Your documents':'나의 서류','NOTES FROM YOUR ADVISOR':'상담사 메모','Updates':'업데이트',
    'STAFF DASHBOARD':'직원 대시보드','Students':'학생','Progress':'진행','Current stage':'현재 단계','Program':'프로그램','Visa':'비자','Visa type':'비자 유형','Status':'상태','Submitted':'제출됨','Approved':'승인됨','Rejected':'거절됨','Other':'기타',
    'Appointment (VFS / embassy)':'예약 (VFS / 대사관)','Note to student':'학생에게 메모','Documents':'서류','Add':'추가','Notes':'메모','Save changes':'변경 사항 저장',
    'Select a student to view and update their progress.':'학생을 선택하여 진행 상황을 확인하고 업데이트하세요.','Students appear here after they sign in to the portal for the first time.':'학생이 포털에 처음 로그인하면 여기에 표시됩니다.','Search students…':'학생 검색…','Search students':'학생 검색','Add a document…':'서류 추가…','Write an update for the student…':'학생에게 업데이트 작성…',
    'Hello, {name}':'안녕하세요, {name}님','You are at step {a} of {b}: {stage}. Next up: {next}.':'현재 {b}단계 중 {a}단계입니다: {stage}. 다음 단계: {next}.','Congratulations — you have completed every step of your journey with us.':'축하합니다 — 저희와 함께한 여정의 모든 단계를 완료하셨습니다.',
    '{a} of {b} received':'{b}개 중 {a}개 수령','Last updated {date}':'마지막 업데이트 {date}','Your Go Go Hankuk advisor':'Go Go Hankuk 상담사','Visa not assigned yet':'비자 미지정',
    'Your advisor will add your document checklist soon.':'상담사가 곧 서류 체크리스트를 추가할 예정입니다.','No updates yet — your advisor will post notes here as your application moves forward.':'아직 업데이트가 없습니다 — 지원이 진행되면 상담사가 이곳에 메모를 남깁니다.',
    'Initial consultation':'초기 상담','We learn about your goals, background and budget.':'목표, 배경, 예산을 파악합니다.','Program selected':'프로그램 선택 완료','Institution and intake confirmed with your advisor.':'상담사와 교육기관 및 입학 시기를 확정했습니다.',
    'Application submitted':'지원서 제출 완료','Documents sent to the institution.':'서류를 교육기관에 보냈습니다.','Certificate of Admission (CoA) issued.':'입학허가서(CoA)가 발급되었습니다.','Visa documents prepared':'비자 서류 준비 완료','Financial proof, forms and photos checked.':'재정증명, 서류, 사진을 확인했습니다.',
    'Visa application submitted':'비자 신청 완료','Biometrics taken at VFS / embassy.':'VFS / 대사관에서 생체정보를 등록했습니다.','Visa approved':'비자 승인','Passport returned with visa.':'비자가 부착된 여권을 받았습니다.','Pre-departure briefing':'출국 전 브리핑','Flights, accommodation and arrival plan.':'항공편, 숙소, 도착 계획.','Arrived & enrolled':'도착 및 등록 완료','Welcome to your new chapter!':'새로운 장을 시작하신 것을 환영합니다!',
    'Missing':'미제출','Under review':'검토 중','Received':'수령 완료','Needs attention':'확인 필요'
  },
  content: {
    hero: { title:'한국에서 공부하세요', description:'당신의 미래는<br>Go Go Education에서 시작됩니다' },
    contact: { note:'미리보기 웹사이트 · 에이전시 연락처 추가 예정' },
    programs: [
      { tag:'한국어', title:'한국어 연수 프로그램', visa:'D-4-1 비자', meta:'대학 부설 어학당 · 6개월~2년', description:'대학 부설 어학당에서 한국어를 배우고 한국에서의 학위 과정이나 취업을 위한 기초를 다지세요.',
        details:'D-4-1(일반연수) 비자는 대학 부설 어학당에서 한국어 과정에 등록한 학생을 위한 비자입니다. 과정은 보통 초급부터 고급까지 6단계로 구성되며 10주 단위 학기로 운영되고, 말하기·듣기·읽기·쓰기 수업이 포함됩니다.\n\n많은 대학이 입학 시 TOPIK 성적이나 어학당 급수 수료를 인정하기 때문에, 한국에서 학사 또는 석사 과정으로 진학하려는 학생들에게 가장 일반적인 첫 단계입니다. 일정 기간 수학 후에는 시간제 취업 허가를 신청할 수도 있습니다.\n\n저희 상담사는 어학당 선택, 입학 및 비자 서류 준비, 숙소와 도착 계획을 도와드립니다. 학비, 입학 시기, 요건은 어학당마다 다르며 상담 시 확인해 드립니다.' },
      { tag:'영어', title:'영어 연수 프로그램', visa:'D-4-7 비자', meta:'한국 내 외국어 연수', description:'한국 캠퍼스 생활을 경험하며 외국어 연수 프로그램을 통해 한국에서 영어를 공부하세요.',
        details:'D-4-7(외국어연수) 비자는 한국의 인가 기관에서 영어 등 외국어 과정에 등록한 학생에게 발급됩니다. 한국 캠퍼스에서 생활하고 공부하면서 국제적인 환경에서 영어 실력을 향상할 수 있습니다.\n\n이 프로그램은 한국이나 다른 나라의 영어 강의 학위 과정으로 진학하기 전에 학업 영어를 강화하고 싶거나, 영어 공부와 한국 문화 체험을 함께 하고 싶은 학생에게 적합합니다.\n\n기관 선택, 등록, 비자 신청, 출국 전 준비까지 안내해 드립니다. 과정 기간, 비용, 입학 요건은 기관과 확인합니다.' },
      { tag:'학사', title:'학사 과정', visa:'D-2-2 비자', meta:'4년제 학위 · 한국어 또는 영어 강의', description:'한국 대학에서 한국어 또는 영어로 진행되는 전공으로 학사 학위를 취득하세요.',
        details:'D-2-2 비자는 한국 대학의 전일제 학사 학위 과정을 위한 비자입니다. 과정은 일반적으로 4년이며 경영, 공학, IT, 디자인, 호텔경영, 인문학 등 다양한 전공이 개설되어 있습니다. 많은 대학이 한국어 과정과 함께 영어 강의 트랙도 운영합니다.\n\n입학에는 보통 고등학교 졸업, 강의 언어에 따른 TOPIK 또는 영어 능력 성적, 성적증명서·학업계획서·재정증명 등의 서류가 필요합니다. 어학 능력이나 학업 성적에 따른 장학금이 흔히 제공됩니다.\n\n저희 팀은 대학 선정, 경쟁력 있는 지원서와 학업계획서 준비, 비자 절차 전 과정을 도와드립니다. 요건과 학비는 대학마다 다르며 상담 시 확인해 드립니다.' },
      { tag:'전문학사', title:'2년제 전문대학 과정', visa:'D-2-1 비자', meta:'전문학사 · 실무 중심 교육', description:'산업체와 긴밀히 연계된 한국 전문대학에서 실무 중심의 2년제 전문학사 학위를 취득하세요.',
        details:'D-2-1 비자는 보통 2~3년 과정인 전문학사(전문대학) 학위 과정을 위한 비자입니다. 한국의 전문대학은 호텔경영, 조리, 뷰티, 자동차, IT, 간호 보조, 관광, 경영 등 분야에서 실무 중심의 직업 교육에 중점을 둡니다.\n\n이 과정은 명확한 취업 경로가 있는 짧고 실무 중심의 자격을 원하거나, 이후 학사 과정으로 편입하려는 학생들에게 인기 있는 경로입니다.\n\n대학과 전공 비교, 어학 및 서류 요건 충족, 입학과 비자 절차 완료까지 도와드립니다. 학비, 입학 시기, 자격 요건은 대학마다 다릅니다.' },
      { tag:'대학원', title:'석사 과정', visa:'D-2-3 비자', meta:'석사 학위 · 연구 및 수업 중심 과정', description:'한국 대학원의 석사 학위로 커리어를 한 단계 발전시키세요.',
        details:'D-2-3 비자는 한국 대학원의 석사 학위 과정을 위한 비자입니다. 과정은 보통 2년이며 경영, 공학, 자연과학, 교육, 국제학 등에서 한국어 및 영어 강의 형태로 모두 개설되어 있습니다.\n\n지원자는 일반적으로 공인 학사 학위, 과정에 맞는 어학 능력 성적, 학업 추천서, 연구 또는 학업 계획서가 필요합니다. 대학원 장학금, 연구 조교, 대학 재정 지원이 유학생에게 자주 제공됩니다.\n\n저희 상담사는 적합한 과정과 지도교수 탐색, 지원서와 서류 준비, 비자 절차 진행을 지원합니다. 요건과 지원금은 대학마다 다릅니다.' },
      { tag:'수도권 진학', title:'수도권 비자 프로그램', visa:'D-2-1 비자', meta:'전문학사 · 서울 수도권 전문대학', description:'D-2-1 비자 유형으로 서울 수도권 교육기관에 중점을 둔 전문대학 진학 경로입니다.',
        details:'수도권 비자 프로그램은 서울 수도권의 전문대학에 중점을 둔 D-2-1 전문학사 진학 경로로, 실무 중심의 2년제 자격을 취득하면서 수도권의 캠퍼스, 시간제 취업 기회, 기업 네트워크를 이용할 수 있습니다.\n\n이 프로그램은 명확하고 체계적인 입학 절차로 서울 근교에서 공부하고 싶은 학생을 위해 마련되었습니다. 개설 전공, 참여 대학, 조건은 매 입학 시기마다 갱신됩니다.\n\n참여 기관 목록, 자격 요건, 학비, 입학 시기는 상담사와 상담하세요.' },
      { tag:'국제 진학 경로', title:'말레이시아→한국·영국 프로그램', visa:'진학 프로그램', meta:'말레이시아에서 먼저 수학 · 한국 또는 영국으로 진학', description:'말레이시아에서 학업을 시작한 뒤 한국 또는 영국의 학위 과정으로 진학하세요.',
        details:'이 경로는 학생이 말레이시아의 파트너 기관에서 파운데이션, 영어 또는 디플로마 과정으로 시작한 후, 한국 또는 영국의 대학으로 편입하여 학위를 마칠 수 있도록 합니다.\n\n말레이시아에서 시작하면 초기 비용이 낮고 영어로 수업을 들으며 국제 유학으로 더 원활하게 전환할 수 있고, 파트너십 구조를 통해 학업 및 어학 조건을 충족하면 명확한 진학 경로가 제공됩니다.\n\n저희 팀은 이용 가능한 경로, 입학 조건, 총 학업 비용을 설명하고 말레이시아, 한국, 영국의 파트너 기관과 지원 절차를 조율합니다. 진학 여부는 각 기관의 요건과 학생의 성적에 따라 달라집니다.' },
      { tag:'국제 진학 경로', title:'태국→한국 프로그램', visa:'진학 프로그램', meta:'태국에서 먼저 수학 · 한국으로 진학', description:'태국의 파트너 기관에서 여정을 시작하고 한국 대학으로 이어가세요.',
        details:'태국→한국 프로그램은 2단계 진학 경로입니다. 학생은 먼저 태국의 파트너 기관에서 준비 과정이나 어학 과정을 마친 뒤 한국의 어학당, 전문대학 또는 대학으로 진학합니다.\n\n이 경로는 한국으로의 큰 이동 전에 가깝고 비용 부담이 적은 곳에서 어학 실력과 학업 준비도를 쌓고 싶은 학생에게 적합하며, 전환의 모든 단계에서 안내를 받을 수 있습니다.\n\n저희 상담사는 현재 파트너 기관, 진학 조건, 각 단계의 비자 절차를 안내해 드립니다. 세부 사항은 상담 시 확인해 드립니다.' }
    ],
    benefits: [
      { title:'당신을 중심으로 한 안내', text:'당신의 관심사, 예산, 속도. 경청에서 시작하는 계획.' },
      { title:'모든 단계에서의 명확성', text:'진행하기 전에 선택지, 서류, 일정을 이해하세요.' },
      { title:'지원 이후에도 계속되는 지원', text:'과정 선택부터 도착 준비까지, 다음에 무엇이 오는지 알 수 있습니다.' }
    ],
    stories: [
      { quote:'앞에 놓인 단계들이 보이자 큰 꿈이 훨씬 더 이룰 수 있는 것으로 느껴졌습니다.', name:'선택지 탐색에서 지원서 준비까지', detail:'학사 과정 여정 예시' },
      { quote:'관심사에 맞춰 과정을 비교해 보니 정말 공부하고 싶은 것이 무엇인지 알 수 있었습니다.', name:'불확실함에서 더 명확한 방향으로', detail:'과정 선택 여정 예시' },
      { quote:'꾸준한 학습 계획 덕분에 더 자신감 있게 영어 준비에 임할 수 있었습니다.', name:'목표 점수에서 주간 학습 계획으로', detail:'어학 학습 여정 예시' }
    ],
    office: [
      { caption:'양곤 시내에 있는 사무실 건물' },{ caption:'학생 상담실' },{ caption:'회의실' },{ caption:'강의실' },
      { caption:'학습 라운지' },{ caption:'상담 공간' },{ caption:'업무 중인 상담팀' },{ caption:'프로그램 자료 및 파트너 자료' }
    ],
    network: [
      { name:'대한민국', note:'대학, 어학당 및 진학 프로그램' },
      { name:'말레이시아', note:'대학 및 칼리지' },
      { name:'태국', note:'대학 및 국제 프로그램' },
      { name:'기타 신흥 글로벌 유학지', note:'전 세계로 파트너십 확대' }
    ]
  }
}
};
